/**
 * Convert a decimal number to a binary array, optionally padded to a certain length
 * Generated by github copilot
 * @param {*} N the denary value to be converted
 * @param {*} length 
 * @returns array of binary digits as strings
 */
function decimalToBinary(N, length = 0) {
    const bin = (N >>> 0).toString(2)
    const padded = length ? bin.padStart(length, '0') : bin
    return padded.split('').reverse()
}

/**
 * Encode an array of permission names into a bitmask integer
 * @param {Array} permissions 
 * @returns Integer value of permission bitmask
 */
function encodePermissionBitmask(permissions) {
    let bitmask = ""
    let permData = global.permData

    permData.reverse().forEach(permission => {
        if (permissions.includes(permission.permissionName)) {
            bitmask += "1"
        } else {
            bitmask += "0"
        }
    })

    return parseInt(bitmask, 2)
}

/**
 * Decode a permission bitmask integer into an object of permission names and boolean values
 * @param {Integer} bitmask 
 * @returns object of permission names and boolean values
 */
function decodePermissionBitmask(bitmask) {
    const permsBinary = decimalToBinary(bitmask)

    let userPerms = {}

    // Split up the binary string and reverse it to match permission order
    // Then iterate through each bit, referencing to the global permissions data and assign permission names accordingly into an object to be returned
    permsBinary.forEach((bit, index) => {
        let permission = global.permData.find(perm => index == perm.bitPos)

        if (bit == "1") {
            userPerms[permission.permissionName] = true
        } else {
            userPerms[permission.permissionName] = false
        }
    })

    return userPerms
}

/**
 * 
 * @param {Array} requiredPerms 
 * @param {Integer} userPerms 
 * @param {String} logicType "AND" or "OR"
 * @returns Boolean
 */
function hasPermissions(requiredPerms, userPerms, logicType = "AND") {
    let decodedUserPerms = decodePermissionBitmask(userPerms)

    if (decodedUserPerms["ADMINISTRATOR"] === true) {
        return true
    } else {
        if (logicType === "OR") {
            // If the logic type is set to OR then only one permission from the requiredPerms array needs to be true
            let accessGranted = false

            requiredPerms.forEach(perm => {
                if (decodedUserPerms[perm] === true) {
                    accessGranted = true
                }
            })

            return accessGranted
        } else {
            // If the logic type is set to AND (Default option) then all permissions from the requiredPerms array need to be true
            let accessGranted = true

            requiredPerms.forEach(perm => {
                if (decodedUserPerms[perm] !== true) {
                    accessGranted = false
                }
            })

        return accessGranted
        }
    }
}

// Filter out columns that are in the exception list
        // Code snippet generated by github copilot
function filterColumns(array, exceptionList) {
    let filteredColumns = array.map(user => {
        let filteredColumn = {}
        Object.keys(user).forEach(key => {
            if (!exceptionList.includes(key)) {
                filteredColumn[key] = user[key]
            }
        })
        return filteredColumn;
    })

    return filteredColumns
}

module.exports = {
    encodePermissionBitmask,
    decodePermissionBitmask,
    hasPermissions,
    filterColumns
}